# Board config for sheepdog-slave --board-config
#
# dtb      : dtb filename under arch/<arch>/boot/dts/<vendor>/
# need_efi : if true, call efi_image.sh after compile to produce efi.bin and dtb.bin

dtb: hamoa-iot-evk.dtb
need_efi: true
rootfs_lable: Rootfs