[LOG]
file = .\linux-sheepdog-master.log
level = DEBUG

[REMOTE]
; addr = 10.64.66.170
addr = 10.64.67.225
; username = yijiyang
username = yanzl
slave_script = ../linux-sheepdog/sheepdog-slave.py
slave_config = ../linux-sheepdog/template-slave.ini
# Refer to the local repo path in remote
; local_repo = ./linux
local_repo = /local/mnt/workspace/upstream/linux/linux-next
# It must be an absolute path
; workspace = /local/mnt/workspace/playarea
workspace = /usr2/yanzl/workspace/linux-sheepdog

[IMAGE]
remote_path = ./
local_path = .\out\
; names = efi.bin
names = boot.img

[DEVICE]
serial_num = 8c1d939e
com_port = COM8
baudrate = 115200